services:
  - type: web
    name: gateway
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/apps/gateway/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false

  - type: web
    name: core
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/apps/core/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: payment
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/apps/payment/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
